version: '3'
services:
  app_seek:
    build:
      context: .
    image: seek-challenge
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://seek_db:3306/seek_challenge?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME: root
      DB_PASSWORD: 1234
      TOKEN_SECRET_KEY: Y2Fubm9uX3Rva2VuX3NlY3JldF9mYWRyZ2Y3ZG5oY25zZGdmZ2dmc3Q=
      TOKEN_USERNAME: andresmen30
      TOKEN_PASSWORD: admin123
      TOKEN_EXPIRATION: 1800000
    restart: always
    depends_on:
      seek_db:
        condition: service_healthy
  seek_db:
    image: mysql:8.0.33
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: seek_challenge
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10